### ISSUE TITLE
Correction suggestions are lowercase when should have been uppercase

### ISSUE THREAD

**Issue by snomos** [divvun/libdivvun#3]
See screenshot:

![skjermbilde 2017-12-11 kl 07 16 33](https://user-images.githubusercontent.com/1255285/33823209-f197eebc-de62-11e7-85a0-730eb9e7f27c.png)

This is a speller error, and as such it should follow the casing of the input word. But one can imagine that we want to detect and correct even casing errors, and I presently do not know how to make that work with the fix for this bug.

**Comment by unhammer** [comment]
In the cases where we explicitly want to correct casing, could we add a tag like `<fixedcase>` in CG to the correction, and if that tag is *not* there, we try to apply input casing? 

So in the above example, there would be no `<fixedcase>` tag, and `divvun-suggest` would look at the word form and conclude that it's titlecased, and apply titlecasing to all suggestions. 

But if you have the CG rule
```
"<Januar>"  COPY (&monthcasing &SUGGESTWF "<januar>" <fixedcase>) IF (NOT -1 CLB) …;
```
then because of the `<fixedcase>`, we wouldn't apply titlecasing to the suggestion.

-----

On a related note, what about sillycasing (`SlinCraze`, `iPhone`)? Currently, this seems to work as it should (try `iPhon ja slinCraze`). I guess the automated input-casing would also have to avoid doing changes where the suggestion is not all lowercase, or where the only change between wordform and suggestion is in casing.

**Comment by snomos** [comment]
`<fixedcase>` seems like a working solution 👍 

sillyCasing: agree with you. In general: lexical case should be preferred, whatever that is, and initial uppercase only applied to all-lowercase words (proper nouns are already uppercased, and sillyCased words should not be touched).

**Comment by snomos** [comment]
Any progress on this one? Using `<fixedcase>` seems fine, and other case handling types can be added later. Essentially, it should go like this:

* if <fixedcase>, suggest generated form
* else, if
** input, suggest inputt
** Input, suggest Inputt
** INPUT, suggest INPUTT
** in any other case (eg inPut) suggest whatever is given by speller (I assume all other cases are marked by the speller), but adjusting initial letter according to input string

Sounds ok?

**Comment by unhammer** [comment]
This goes not just for spelling, but for stuff added with &SUGGEST too, right?

**Comment by snomos** [comment]
yes
